version: '3.4'

services:
  postgres:
    container_name: r_twitter_postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/data/pg
    restart: always
    environment:
      POSTGRES_PASSWORD: psss11rwere
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - postgres

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redis:
    driver: local
